const PortfolioData = [
  // free====================================================================================
  {
    date: "2015 to 2024",
    hd: "Other Projects",
    folderName: "free",
    items: [
      { name: "dubai-visa", domain: "com", },
      { name: "rajankapoorchai", domain: "com", status: true },
    ],
  },
  // bls====================================================================================
  {
    date: "9 May 2015 to 9 June 2016",
    hd: "BLS International Services Ltd.",
    folderName: "bls",
    items: [
      { name: "india.blsattestation", domain: "com", note:true, status:true },
      { name: "visasoftheworld", domain: "in", },
      { name: "digitized-it", domain: "com", },
      { name: "blsindiavisa-uae", domain: "com", status:true },
      { name: "blsindia", domain: "sg", },
      { name: "blsindiavisa-austria", domain: "com", },
      { name: "blsindia-canada", domain: "com", status:true },
      { name: "blsindia-china", domain: "com", },
      { name: "blsindia-hongkong", domain: "com", },
      { name: "blsisrael-ken", domain: "com", },
      { name: "blsindiavisa-lithuania", domain: "com", },
      { name: "blsindia-norway", domain: "com", },
      { name: "blsindia-oman", domain: "com", },
      { name: "blsindiavisa-ph", domain: "com", },
      { name: "blsindiavisa-poland", domain: "com", },
      { name: "blsindia-russia", domain: "com", },
      { name: "blshungary-azerbaijan", domain: "com", },
      { name: "getdubaivisa", domain: "com", },
      { name: "bls-malaysia", domain: "com", },
      { name: "blsindia-malaysia", domain: "com", }
    ],
  },
  // city====================================================================================
  {
    date: "10 June 2016 to 28 Feb 2017",
    hd: "City Vacations Pvt. Ltd.",
    folderName: "city",
    items: [
      { name: "ticketstoworld", domain: "co.uk", status: true},
      { name: "ticketstoindia", domain: "co.uk", status: true},
      { name: "ticketstousa", domain: "co.uk", status: true},
      { name: "ticketstopakistan", domain: "co.uk", status: true},
      { name: "myamsterdam", domain: "co.uk", status: true},
      { name: "citybreak1", domain: "co.uk", status: true},
    ],
  },
  // snva====================================================================================
  {
    date: "1 Feb 2017 to 12 Nov 2021",
    hd: "SNVA Ventures Pvt. Ltd.",
    folderName: "snva",
    items: [
      { name: "travomint", domain: "com", note:true, status:true },
      { name: "careerera", domain: "com", note:true, status:true },
      { name: "7qasearch", domain: "com", },
      { name: "a2znumber", domain: "com", },
      { name: "airlineschange", domain: "com", },
      { name: "allphonesupport", domain: "com", },
      { name: "allsupportno", domain: "com", },
      { name: "supportno", domain: "com", },
      { name: "alltfn", domain: "com", status:true },
      { name: "alternativenumber", domain: "com", },
      { name: "anvsupport", domain: "com", },
      { name: "askpromptly", domain: "com", },
      { name: "changemyflights", domain: "com", status:true },
      { name: "cheapflightinfo", domain: "com", },
      { name: "codingversity", domain: "org", },
      { name: "contactforhelpnumber", domain: "com", },
      { name: "csversity", domain: "org", },
      { name: "dmversity", domain: "org", },
      { name: "dsversity", domain: "org", },
      { name: "ebiztown", domain: "com", },
      { name: "emailcustomerservicehelp", domain: "com", },
      { name: "fareodeal", domain: "com", },
      { name: "faresboutique", domain: "com", status:true },
      { name: "faresglob", domain: "com", },
      { name: "fareskhalifa", domain: "com", },
      { name: "flycoair", domain: "com", status:true },
      { name: "fortuneserve", domain: "com", },
      { name: "gethelpnumber", domain: "com", status:true },
      { name: "globalinfonic", domain: "com", },
      { name: "gmailfaqs", domain: "com", },
      { name: "gmailsphonenumber", domain: "com", },
      { name: "gmailsupportpedia", domain: "com", },
      { name: "guidebuz", domain: "com", },
      { name: "helplinenos", domain: "com", },
      { name: "helpquicky", domain: "com", status:true },
      { name: "helpskey", domain: "com", status:true },
      { name: "helptechsupportnumber", domain: "com", },
      { name: "herehelpu", domain: "com", },
      { name: "hotmailcustomercare", domain: "com", status:true },
      { name: "hotmailtechsupport", domain: "com", },
      { name: "hubcustomersupport", domain: "com", },
      { name: "infohouze", domain: "com", },
      { name: "infoopedia", domain: "com", status:true },
      { name: "instohelp", domain: "com", },
      { name: "invoicefundingsolutions", domain: "com", },
      { name: "isupportnumber", domain: "com", },
      { name: "itfixtech", domain: "com", },
      { name: "ithelpnumber", domain: "com", },
      { name: "learnaside", domain: "com", status:true },
      { name: "learningua", domain: "com", },
      { name: "livegeekschat", domain: "net", },
      { name: "lookatfares", domain: "com", },
      { name: "majestytravels", domain: "com", },
      { name: "myfaresadda", domain: "com", },
      { name: "myteches", domain: "com", },
      { name: "nitroinfotech", domain: "com", },
      { name: "nobelapp", domain: "net", status:true },
      { name: "numberforhelp", domain: "com", },
      { name: "numberreviews", domain: "com", },
      { name: "nyitm", domain: "com", },
      { name: "psupportnumber", domain: "com", },
      { name: "pwsupportnumber", domain: "com", },
      { name: "questohub", domain: "com", },
      { name: "quickcaribbean", domain: "com", },
      { name: "quicklatino", domain: "com", },
      { name: "quickosupport", domain: "com", },
      { name: "quicktechnicalsupport", domain: "com", },
      { name: "reservationsdeal", domain: "com", },
      { name: "reservationssticket", domain: "com", },
      { name: "snva", domain: "com", },
      { name: "ss-geeks", domain: "com", status:true },
      { name: "tecask", domain: "com", },
      { name: "thelabelbar", domain: "com", },
      { name: "thelivexperts", domain: "com", },
      { name: "tracingpage", domain: "com", status:true },
      { name: "tripocost", domain: "com", status:true },
      { name: "vic2soft", domain: "com", },
      { name: "way2career", domain: "co", },
      { name: "ysupportnumber", domain: "com", },
      { name: "versity", domain: "in", status:true },
      { name: "holidaytanks", domain: "com", },
      { name: "flightszoom", domain: "co.uk", },
      { name: "flightszoom", domain: "com", },
      { name: "phdversity", domain: "com", },
      { name: "aasthahomes", domain: "com", },
      { name: "travomint", domain: "co.uk", },
      { name: "traveloes", domain: "co.uk", },
      { name: "traveloes", domain: "com", },
      { name: "cheapflightadvisor", domain: "com", },
      { name: "flightrouteinfo", domain: "com", status:true },
      { name: "onlinegamesupportplus", domain: "com", },
      { name: "routersupportplus", domain: "com", },
      { name: "printersupportplus", domain: "com", },
      { name: "antivirusupportplus", domain: "com", },
      { name: "desktopsupportplus", domain: "com", },
      { name: "emailsupportplus", domain: "com", },
      { name: "computerssupportplus", domain: "com", },
      { name: "mobilesupportplus", domain: "com", },
      { name: "webmailsupportplus", domain: "com", },
      { name: "internetsupportplus", domain: "com", },
      { name: "browsersupportplus", domain: "com", },
      { name: "hardwaresupportplus", domain: "com", },
      { name: "modemsupportplus", domain: "com", },
      { name: "laptopsupportplus", domain: "com", },
      { name: "websitesupportplus", domain: "com", },
      { name: "passwordrecoverysupportplus", domain: "com", },
      { name: "windowssupportplus", domain: "com", },
      { name: "echeck360", domain: "com", },
      { name: "uni-versity", domain: "in", },
      { name: "sixsigmaversity", domain: "org", },
      { name: "laruetreefarm", domain: "com", },
      { name: "uhawaii", domain: "org", },
      { name: "edukasion", domain: "com", },
      { name: "highriskgateway", domain: "in", },
      { name: "honorary-phd", domain: "com", },
      { name: "icasr", domain: "org", },
      { name: "american", domain: "uni", },
      { name: "ehelplinenumber", domain: "com", },
      { name: "anpuhelp", domain: "com", },
      { name: "askbuz", domain: "com", },
      { name: "instanttfn", domain: "com", },
      { name: "fixtechhelp", domain: "com", },
      { name: "etechhelps", domain: "com", },
      { name: "vikuhelp", domain: "com", },
      { name: "searchangout", domain: "com", },
      { name: "bigpbx", domain: "com", },
      { name: "cyberzoomlabs", domain: "com", },
      { name: "buzzmeweb", domain: "com", },
      { name: "travel26", domain: "com", },
      { name: "itphonenumber", domain: "com", },
      { name: "ifixscotland", domain: "com", },
      { name: "executivemba", domain: "online", },
      { name: "subharti", domain: "uni", },
      { name: "cheapflighto", domain: "net", },
      { name: "nextecdubai", domain: "com", },
      { name: "vizmedia360", domain: "com", },
      { name: "computersrevolution", domain: "com", },
      // { name: "flightsbuddy", domain: "co.uk", },
      { name: "bookmyflightticket", domain: "com", },
      // { name: "onsitetechies", domain: "org", },
      { name: "flightstrade", domain: "com", },
      { name: "etechys", domain: "com", },
      { name: "epasswordrecovery", domain: "com", },
      { name: "supportonphone", domain: "com", },
      { name: "fasttechhub", domain: "com", },
      { name: "bba-admission", domain: "com", },
      { name: "bca-admission", domain: "com", },
      { name: "mbaadmission2018", domain: "com", },
      { name: "bed-admission", domain: "in", },
      { name: "cyberzoom", domain: "net", },
      { name: "eximiussolution", domain: "com", },
      { name: "fareguru", domain: "co.uk", },
      { name: "faretrolly", domain: "com", },
      { name: "faretrust", domain: "co.uk", },
      { name: "faretrust", domain: "com", },
      { name: "gizmomarvel", domain: "com", },
      { name: "itechnoinc", domain: "net", },
      { name: "onetechies", domain: "com", },
      { name: "onsitesolution", domain: "org", },
      { name: "passwordresetsupportplus", domain: "com", },
      { name: "reservationss", domain: "com", },
      { name: "scrumversity", domain: "org", status:true },
      { name: "snvabpo", domain: "com", },
      { name: "tophelpline", domain: "com", },
      { name: "touraza", domain: "com", },
      { name: "travohelp", domain: "com", status:true },
      { name: "travomart", domain: "com", },
      { name: "vialra", domain: "com", }
    ],
  },
  // si====================================================================================
  {
    date: "13 Nov 2022 to 13 May 2023",
    hd: "SynapseIndia Outsourcing Pvt. Ltd.",
    folderName: "si",
    items: [
      { name: "alefmeem", domain: "store",},
      { name: "stemcityusa", domain: "com", status:true },
      { name: "osmosalt", domain: "com", status:true },
    ],
  },
  // i2a====================================================================================
  {
    date: "23 May 2022 to Present",
    hd: "I2A Technologies Pvt. Ltd.",
    folderName: "i2a",
    items: [
      { name: "9cents", domain: "com", status:true },
      { name: "akounto", domain: "com" },
      { name: "akountobooks", domain: "com" },
      { name: "askairlinesofficial", domain: "com", status:true },
      { name: "reservations", domain: "us", status:true },
      { name: "trading-9cents", domain: "com" },
      { name: "uniquote", domain: "com" },
      { name: "oceanvivid", domain: "com", status:true },
      { name: "travelocean", domain: "us" },
      { name: "rentedcar", domain: "au", status:true },
      { name: "exotic-car-rentals", domain: "com" },
      { name: "rented-car", domain: "com", status:true },
      { name: "bookinghotel", domain: "us" },
      { name: "esflights", domain: "com", status:true },
      { name: "lowprice-site", domain: "com" },
      { name: "lowpricecarrental", domain: "com", status:true },
      { name: "cruise-travels", domain: "com", status:true },
      { name: "thetravelconnection", domain: "us", status:true },
      { name: "orbcruise", domain: "com" },
      { name: "primetradefx", domain: "com" },
      { name: "exterminatorcall", domain: "com", status:true },
      { name: "trekhops", domain: "com", status:true },
      { name: "99xtrade", domain: "com" },
      { name: "zippyconvert", domain: "com", status:true },
      { name: "800bookkeeping", domain: "com" },
      { name: "orbtickets", domain: "com", status:true },
      { name: "cheaprented", domain: "com", status:true },
      { name: "rentalfare", domain: "com" },
      { name: "topcruisings", domain: "com" },
      { name: "vipsailings", domain: "com" },
      { name: "egenbooks", domain: "com", status:true },
      { name: "oceanfares", domain: "com", status:true },
      { name: "premiumaccounting", domain: "us", status:true },
      { name: "rentfares", domain: "com", status:true },
      { name: "tookoff", domain: "com", status:true }
    ]
  },
].reverse();

export default PortfolioData;